### ISSUE TITLE
Select/Reject samples during training

### ISSUE THREAD

**Issue by xhchen10** [s-sd/task-amenability#3]
Hi Shaheer, thanks for proposing such pioneering works.

I have some concerns about your training process. I can not find the codes for selecting or rejecting samples with high task amenability to retrain the actor (task predictor). I could only find similar codes for evaluating/testing in L125 of pneumoniamnist_experiment.py. Could you please indicate where similar codes for selecting and retraining are?

Best.

**Comment by s-sd** [comment]
Hi @xhchen10! Sorry but I had not originally added the selection-based reward scheme to the repo. I will add this, hopefully by the end of today and will tag you and mark this issue as closed, once I have added it.

**Comment by s-sd** [comment]
Please see PR #4, now merged to main.

Please note that:

The original was tested with code written without an interface. The added code has been adapted to fit within the interface (for improved usability and readability) and thus not extensively tested.

Note main changes from the weighted reward in `envs/task_amenability.py` are: 

1) the use of `val_sel_ratio` to initialise the environment (specified what proportion of samples to select for reward computation) 

2) addition of a `get_val_sel_reward` function to compute the selection based reward (select the highest rated `val_sel_ratio` and average the accuracy over these) 

3) use of this function to compute the validation metric `line 100`

**Comment by s-sd** [comment]
Hi @xhchen10! I have now merged the validation set selection-based reward to main. Please see the description in PR #4 and above for further details.

I will now close this issue but if any other questions etc., please feel free to send me an email/ open a new issue on the repo.

Thanks.
